// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewNote struct {
	Text string `json:"text"`
}

type Note struct {
	ID      string  `json:"id"`
	Text    string  `json:"text"`
	Done    bool    `json:"done"`
	Users   []*User `json:"users"`
	Deleted bool    `json:"deleted"`
}

type Time struct {
	UnixTime  int    `json:"unixTime"`
	TimeStamp string `json:"timeStamp"`
}

type User struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Notes []*Note `json:"notes"`
}
